### ISSUE TITLE
correct import?

### ISSUE THREAD

**Issue by rdutoit** [KingIsulgard/iOS-InApp-Settings-TableView#1]
Nice piece of code. Thanks.
I notice the import statement #import "SettingsController.h" in MultiValueTableViewController.h class. I assume you mean "SettingsTableViewController.h"? 

Also as the code stands the MultiValueDelegate  is not recognized in the line below in SettingsTableViewController.h?  I can get the table setup in SettingsTableViewController therefore but not in MultiValueTableViewController.h. Thanks, Rob

@interface SettingsTableViewController : UITableViewController <MultiValueDelegate>

**Comment by KingIsulgard** [comment]
I removed the SettingsController.h reference. It is a class I used myself to load my Settings but I adapted this code to write directly to the settings bundle. I accidentally left that reference in there.

The MultiValueDelegate is defined in the MultiValueTableViewController.h file. This probably gave an error because of the dead reference to the SettingsController. Try to remove that reference. I also removed it in this git. Thanks for the feedback.
